CREATE TABLE [dbo].[Bill]
(
	[Number] BIGINT NOT NULL PRIMARY KEY IDENTITY
   ,Created DATETIME2 NOT NULL DEFAULT GETDATE()
   ,[Status] INT NOT NULL FOREIGN KEY REFERENCES [BillStatus]([Id]) DEFAULT 0
)
