CREATE TABLE [dbo].[Item]
(
	[BillNumber] BIGINT NOT NULL FOREIGN KEY REFERENCES Bill(Number)
   ,[Barcode] BIGINT NOT NULL FOREIGN KEY REFERENCES Product(Barcode) ON DELETE NO ACTION ON UPDATE NO ACTION
   ,[Name] NVARCHAR(100) NOT NULL
   ,[Price] DECIMAL(15,2) NOT NULL
   ,[Quantity] FLOAT(24) NOT NULL DEFAULT 1
)
