// <auto-generated />
using System;
using CashierDB.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CashierDB.Migrations
{
    [DbContext(typeof(CashierContext))]
    partial class CashierContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CashierDB.Model.DTO.BillDbDto", b =>
                {
                    b.Property<long>("Number_")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<int>("StatusId")
                        .HasColumnType("int")
                        .HasColumnName("Status");

                    b.HasKey("Number_");

                    b.HasIndex("StatusId");

                    b.ToTable("Bill");
                });

            modelBuilder.Entity("CashierDB.Model.DTO.BillStatusDbDto", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("BillStatus");

                    b.HasData(
                        new
                        {
                            Id = 0,
                            Name = "Открыт"
                        },
                        new
                        {
                            Id = 1,
                            Name = "Закрыт"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Отмена"
                        });
                });

            modelBuilder.Entity("CashierDB.Model.DTO.ItemDbDto", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Amount")
                        .HasColumnType("float");

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasColumnType("char(13)");

                    b.Property<long>("BillNumber")
                        .HasColumnType("bigint")
                        .HasColumnName("Bill");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("Barcode");

                    b.HasIndex("BillNumber");

                    b.ToTable("Item");
                });

            modelBuilder.Entity("CashierDB.Model.DTO.ProductDbDto", b =>
                {
                    b.Property<string>("Barcode")
                        .HasColumnType("char(13)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Barcode");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("CashierDB.Model.DTO.BillDbDto", b =>
                {
                    b.HasOne("CashierDB.Model.DTO.BillStatusDbDto", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Status");
                });

            modelBuilder.Entity("CashierDB.Model.DTO.ItemDbDto", b =>
                {
                    b.HasOne("CashierDB.Model.DTO.ProductDbDto", "Product")
                        .WithMany()
                        .HasForeignKey("Barcode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CashierDB.Model.DTO.BillDbDto", "Bill")
                        .WithMany("Items")
                        .HasForeignKey("BillNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bill");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("CashierDB.Model.DTO.BillDbDto", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
